// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgRHXHxwgDtZKRwcf-BzWW1BX-sFmxAgQ',
    appId: '1:318540066373:web:fc38dbdce4780999bdbd2c',
    messagingSenderId: '318540066373',
    projectId: 'justdontcrash-b7164',
    authDomain: 'justdontcrash-b7164.firebaseapp.com',
    storageBucket: 'justdontcrash-b7164.firebasestorage.app',
    measurementId: 'G-JPB73QKSGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsA2A_8kKNKOctUkx9YUGx0f2TEbwnR2s',
    appId: '1:318540066373:android:c767291acd44aae0bdbd2c',
    messagingSenderId: '318540066373',
    projectId: 'justdontcrash-b7164',
    storageBucket: 'justdontcrash-b7164.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRpjU2z3JLl71K7F5AqKAZnijkXAiI-kI',
    appId: '1:318540066373:ios:d58c24f275c5193dbdbd2c',
    messagingSenderId: '318540066373',
    projectId: 'justdontcrash-b7164',
    storageBucket: 'justdontcrash-b7164.firebasestorage.app',
    iosBundleId: 'com.example.jdcMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRpjU2z3JLl71K7F5AqKAZnijkXAiI-kI',
    appId: '1:318540066373:ios:d58c24f275c5193dbdbd2c',
    messagingSenderId: '318540066373',
    projectId: 'justdontcrash-b7164',
    storageBucket: 'justdontcrash-b7164.firebasestorage.app',
    iosBundleId: 'com.example.jdcMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgRHXHxwgDtZKRwcf-BzWW1BX-sFmxAgQ',
    appId: '1:318540066373:web:2d65739a19858d03bdbd2c',
    messagingSenderId: '318540066373',
    projectId: 'justdontcrash-b7164',
    authDomain: 'justdontcrash-b7164.firebaseapp.com',
    storageBucket: 'justdontcrash-b7164.firebasestorage.app',
    measurementId: 'G-C460P5FKD0',
  );
}
